const images = {
    game: {
        [1]: {
            backgrounds: {
                [1]: require("../assets/game/1/background/1.webp"),
            },
            objectives: {
                [1]: require("../assets/game/1/objectives/1.webp"),
                [2]: require("../assets/game/1/objectives/2.webp"),
                [3]: require("../assets/game/1/objectives/3.webp"),
                [4]: require("../assets/game/1/objectives/4.webp"),
                [5]: require("../assets/game/1/objectives/5.webp"),
                [6]: require("../assets/game/1/objectives/6.webp"),
                [7]: require("../assets/game/1/objectives/7.webp"),
                [8]: require("../assets/game/1/objectives/8.webp"),
                [9]: require("../assets/game/1/objectives/9.webp"),
                [10]: require("../assets/game/1/objectives/10.webp"),
            },
            props: {
                [1]: require("../assets/game/1/props/1.webp"),
                [2]: require("../assets/game/1/props/2.webp"),
                [3]: require("../assets/game/1/props/3.webp"),
                [4]: require("../assets/game/1/props/4.webp"),
                [5]: require("../assets/game/1/props/5.webp"),
                [6]: require("../assets/game/1/props/6.webp"),
                [7]: require("../assets/game/1/props/7.webp"),
                [8]: require("../assets/game/1/props/8.webp"),
                [9]: require("../assets/game/1/props/9.webp"),
                [10]: require("../assets/game/1/props/10.webp"),
                [11]: require("../assets/game/1/props/11.webp"),
                [12]: require("../assets/game/1/props/12.webp"),
                [13]: require("../assets/game/1/props/13.webp"),
                [14]: require("../assets/game/1/props/14.webp"),
                [15]: require("../assets/game/1/props/15.webp"),
                [16]: require("../assets/game/1/props/16.webp"),
                [17]: require("../assets/game/1/props/17.webp"),
                [18]: require("../assets/game/1/props/18.webp"),
                [19]: require("../assets/game/1/props/19.webp"),
                [20]: require("../assets/game/1/props/20.webp"),
                [21]: require("../assets/game/1/props/21.webp"),
                [22]: require("../assets/game/1/props/22.webp"),
                [23]: require("../assets/game/1/props/23.webp"),
                [24]: require("../assets/game/1/props/24.webp"),
                [25]: require("../assets/game/1/props/25.webp"),
                [26]: require("../assets/game/1/props/26.webp"),
                [27]: require("../assets/game/1/props/27.webp"),
                [28]: require("../assets/game/1/props/28.webp"),
                [29]: require("../assets/game/1/props/29.webp"),
                [30]: require("../assets/game/1/props/30.webp"),
                [31]: require("../assets/game/1/props/31.webp"),
                [32]: require("../assets/game/1/props/32.webp"),
                [33]: require("../assets/game/1/props/33.webp"),
                [34]: require("../assets/game/1/props/34.webp"),
            },
        },
    },

    found: require("../assets/found.png"),
}

export default images
