const images = {
    game: {
        [1]: {
            backgrounds: {
                [1]: require("../assets/game/1/background/1.webp"),
                [2]: require("../assets/game/1/background/2.webp"),
                [3]: require("../assets/game/1/background/3.webp"),
            },
            objectives: {
                [1]: { url: require("../assets/game/1/objectives/coelho_1a.webp"), width: 35, height: 55 },
                [2]: { url: require("../assets/game/1/objectives/coelho_1b.webp"), width: 35, height: 55 },
                [3]: { url: require("../assets/game/1/objectives/coelho_2a.webp"), width: 35, height: 55 },
                [4]: { url: require("../assets/game/1/objectives/coelho_2b.webp"), width: 35, height: 55 },
                [5]: { url: require("../assets/game/1/objectives/coelho_3a.webp"), width: 35, height: 55 },
                [6]: { url: require("../assets/game/1/objectives/coelho_3b.webp"), width: 35, height: 55 },
                [7]: { url: require("../assets/game/1/objectives/coelho_4a.webp"), width: 35, height: 55 },
                [8]: { url: require("../assets/game/1/objectives/coelho_4b.webp"), width: 35, height: 55 },
                [9]: { url: require("../assets/game/1/objectives/coelho_5a.webp"), width: 35, height: 55 },
                [10]: { url: require("../assets/game/1/objectives/coelho_5b.webp"), width: 35, height: 55 },
            },
            scenery: {
                [1]: { url: require("../assets/game/1/scenery/arbusto_5.webp"), width: 75, height: 40 },
                [2]: { url: require("../assets/game/1/scenery/arbusto_4.webp"), width: 75, height: 50 },
                [3]: { url: require("../assets/game/1/scenery/arbusto_3.webp"), width: 55, height: 50 },
                [4]: { url: require("../assets/game/1/scenery/arbusto_2.webp"), width: 65, height: 50 },
                [5]: { url: require("../assets/game/1/scenery/arbusto_1.webp"), width: 75, height: 50 },
                [6]: { url: require("../assets/game/1/scenery/arvore_1.webp"), width: 95, height: 120 },
                [7]: { url: require("../assets/game/1/scenery/arvore_2.webp"), width: 95, height: 130 },
                [8]: { url: require("../assets/game/1/scenery/arvore_3.webp"), width: 70, height: 80 },
                [9]: { url: require("../assets/game/1/scenery/arvore_4.webp"), width: 95, height: 125 },
                [10]: { url: require("../assets/game/1/scenery/arvore_5.webp"), width: 95, height: 110 },
                [11]: { url: require("../assets/game/1/scenery/arvore_6.webp"), width: 60, height: 60 },
                [12]: { url: require("../assets/game/1/scenery/arvore_7.webp"), width: 95, height: 80 },
                [13]: { url: require("../assets/game/1/scenery/arvore_8.webp"), width: 90, height: 90 },
            },
            props: {
                [1]: { url: require("../assets/game/1/props/animal_aranha.webp"), width: 60, height: 60 },
                [2]: { url: require("../assets/game/1/props/animal_borboleta.webp"), width: 60, height: 60 },
                [3]: { url: require("../assets/game/1/props/animal_cachorro.webp"), width: 60, height: 60 },
                [4]: { url: require("../assets/game/1/props/animal_caracol.webp"), width: 60, height: 60 },
                [5]: { url: require("../assets/game/1/props/animal_esquilo.webp"), width: 60, height: 60 },
                [6]: { url: require("../assets/game/1/props/animal_galinha.webp"), width: 60, height: 60 },
                [7]: { url: require("../assets/game/1/props/animal_jacare.webp"), width: 60, height: 60 },
                [8]: { url: require("../assets/game/1/props/animal_joaninha.webp"), width: 60, height: 60 },
                [9]: { url: require("../assets/game/1/props/animal_lagartixa.webp"), width: 60, height: 60 },
                [10]: { url: require("../assets/game/1/props/animal_lobo.webp"), width: 60, height: 60 },
                [11]: { url: require("../assets/game/1/props/animal_macaco.webp"), width: 60, height: 60 },
                [12]: { url: require("../assets/game/1/props/animal_minhoca.webp"), width: 60, height: 60 },
                [13]: { url: require("../assets/game/1/props/animal_morcego.webp"), width: 60, height: 60 },
                [14]: { url: require("../assets/game/1/props/animal_peixe.webp"), width: 60, height: 60 },
                [15]: { url: require("../assets/game/1/props/animal_raposa.webp"), width: 60, height: 60 },
                [16]: { url: require("../assets/game/1/props/animal_sapo.webp"), width: 60, height: 60 },
                [17]: { url: require("../assets/game/1/props/bola_futebol_1.webp"), width: 60, height: 60 },
                [18]: { url: require("../assets/game/1/props/bola_futebol_2.webp"), width: 60, height: 60 },
                [19]: { url: require("../assets/game/1/props/bola_futebol_3.webp"), width: 60, height: 60 },
                [20]: { url: require("../assets/game/1/props/bola_futebol_4.webp"), width: 60, height: 60 },
                [21]: { url: require("../assets/game/1/props/bola_futebol_5.webp"), width: 60, height: 60 },
                [22]: { url: require("../assets/game/1/props/bola_praia.webp"), width: 60, height: 60 },
                [23]: { url: require("../assets/game/1/props/bola_volei.webp"), width: 60, height: 60 },
                [24]: { url: require("../assets/game/1/props/bola_basquete.webp"), width: 60, height: 60 },
                [25]: { url: require("../assets/game/1/props/comida_algodao_doce.webp"), width: 60, height: 60 },
                [26]: { url: require("../assets/game/1/props/comida_bolo.webp"), width: 60, height: 60 },
                [27]: { url: require("../assets/game/1/props/comida_bom_bom.webp"), width: 60, height: 60 },
                [28]: { url: require("../assets/game/1/props/comida_brigadeiro.webp"), width: 60, height: 60 },
                [29]: { url: require("../assets/game/1/props/comida_cheesecake.webp"), width: 60, height: 60 },
                [30]: { url: require("../assets/game/1/props/comida_chocolate.webp"), width: 60, height: 60 },
                [31]: { url: require("../assets/game/1/props/comida_donut.webp"), width: 60, height: 60 },
                [32]: { url: require("../assets/game/1/props/comida_pirulito.webp"), width: 60, height: 60 },
                [33]: { url: require("../assets/game/1/props/comida_pudim.webp"), width: 60, height: 60 },
                [34]: { url: require("../assets/game/1/props/comida_sorvete.webp"), width: 60, height: 60 },
            },
        },
    },

    found: require("../assets/found.webp"),
    onPress: require("../assets/onPress.png"),
}

export default images
